#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SConstruct (Python)
# 
# Purpose: Build the velocity model.
# 
# Site: https://dirack.github.io
# 
# Version 1.0
# 
# Programmer: Rodolfo A C Neves (Dirack) 18/08/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Madagascar package
from rsf.proj import *

# Recipes
from rsf.recipes.kimodel import multiLayerModel as mlmod

# Original velocity model
xmax = 6.0
zmax = 4.0

layers = ((1.00,1.20,0.90,1.00),
          (1.85,1.85,1.85,1.85))

velocities = (1.508,
              1.690,
              2.0)

# Generate multi layer model
mlmod(interfaces='interfaces',
        dipsfile='interfacesDip',
        modelfile='model',
        xmax=xmax,
        zmax=zmax,
        layers=layers,
        velocities=velocities)

# plot the model
Plot('model','model',
	'''
	grey color=j scalebar=y label1=Depth unit1=km label2=Position unit2=km barlabel=Velocity barunit=km/s barreverse=y title="Velocity Model" allpos=yi bias=1.0
	''')
